set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g status-position top
set -g status-style bg=#1e1e2e,fg=#cdd6f4

set -g window-status-current-style bg=#313244,fg=#cba6f7
set -g window-status-activity-style bg=#313244,fg=#f38ba8

set -g base-index 1
set -g pane-base-index 1

set -g pane-active-border-style fg=#cba6f7

set -g mouse on

set -g allow-passthrough on

bind | split-window -h
bind - split-window -v
bind -T copy-mode-vi v send -X selection-mode
bind -T copy-mode-vi y send -X copy-selection-and-cancel

set -g default-terminal "screen-256color"

set -g status-interval 1
set -g status-left-length 30
set -g status-right-length 50